### PR TITLE
Home Page UI Implementation

### PR DESCRIPTION
**Pull request by KevinTran000**
Change Log:
- Renamed old `Home` to `dashboard` to better represent its contents
- Made new `Home` to actually represent the home page (3 buttons, Students, Admin, Volunteer login buttons)
- Added additional routes, for when user is authenticated, but tried to go direct to login, redirect immediately to `/dashboard` instead.
- Moved home from `./src/containers` to `./src/containers/home` structure. Reasoning is for `./src/container/home/images` to store relevant images belonging to home.
- Added `I am...` h1 text.
- Added 2 buttons (Students and Administrator)
- Added image files for use in buttons.
- Added drop shadow to new buttons.
- Fiddled with flexbox layout options.

- [Bug Fix]: Fixed incorrect destination for Dashboard link in sidebar.

### CODE REVIEW

**Comment by KevinTran000** [comment]
Please review work and ensure:
- Still works
- No additional bugs were added
- Fulfills the objective we were given for this sprint
- Give any further opinions and/or comments

Edited: At this time the UI looked like this, matching the model provided.
Screenshot_2019-04-01 React App

**Comment by KevinTran000** [comment]
@adhikaribiraj has few suggestions/changes/additions to make before this PR can be merged. Holding actual merge. 

Holding this PR up to Wednesday, March 13, 2019. After that point, this PR must be reviewed and merged and then we can open up PR to main repo for those guys to review and merge!

**Comment by KevinTran000** [comment]
At this time, the UI looks like this:
Screenshot_2019-04-01 React App(1)

**Comment by adhikaribiraj** [comment]
After the latest commits, this is the final look of the landing page:
Screen Shot 2019-04-01 at 2 02 45 PM

**Comment by KevinTran000** [comment]
Resolved Merge conflicts

**Comment by KevinTran000** [comment]
PR was incorporated upstream.

**Pull request merged**
